project_name: gotham

before:
  hooks:
    - go mod download

builds:
  - goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/gothamhq/gotham/common/hugo.buildDate={{.Date}} -X github.com/gothamhq/gotham/common/hugo.commitHash=

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: macos
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-macos-amd64-checksum.txt"

changelog:
  skip: true

brews:
  - github:
      owner: gothamhq
      name: homebrew-tap
    commit_author:
      name: "GoReleaser"
      email: GoReleaser@GothamHQ.com
    folder: Formula
    homepage: "https://GothamHQ.com"
    description: "An awesome static site generator based on Hugo."
    dependencies:
      - name: go
    test: |
      site = testpath/"hops-yeast-malt-water"
      system "#{bin}/gotham", "new", "site", site
      assert_predicate testpath/"#{site}/config.toml", :exist?
