project_name: strawberry

builds:
  - dir: src
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      #  -extldflags "-static" is purposely left out on macOS due to compiling libSASS
      - -s -w -X github.com/strawberryssg/strawberry-v0/common/hugo.buildDate={{.Date}} -X github.com/strawberryssg/strawberry-v0/common/hugo.commitHash={{ .ShortCommit }}

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: macos
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-macos-amd64-checksum.txt"

changelog:
  skip: true

brews:
  - tap:
      owner: strawberryssg
      name: homebrew-tap
    commit_author:
      name: "GoReleaser"
      email: FelicianoTech@gmail.com
    folder: Formula
    homepage: "https://www.StrawberrySSG.com"
    description: "An awesome static site generator based on Hugo."
    dependencies:
      - name: go
    test: |
      site = testpath/"hops-yeast-malt-water"
      system "#{bin}/strawberry", "new", "site", site
      assert_predicate testpath/"#{site}/config.toml", :exist?
