project_name: gotham

builds:
  - id: gotham-linux
    dir: src
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/gothamhq/gotham/common/hugo.buildDate={{.Date}} -X github.com/gothamhq/gotham/common/hugo.commitHash={{ .ShortCommit }} -extldflags "-static"
  - id: gotham-windows
    dir: src
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -buildmode
      - exe
      - -tags
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/gothamhq/gotham/common/hugo.buildDate={{.Date}} -X github.com/gothamhq/gotham/common/hugo.commitHash={{ .ShortCommit }}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-linux-windows-amd64-checksum.txt"

#nfpms:
  #-
    #builds:
    #  - linux
    #formats:
    #    - deb
    #vendor: "GothamHQ"
    #homepage: "https://GothamHQ.com"
    #maintainer: "GothamHQ Team <Team@GothamHQ.com>"
    #description: "An awesome static site generator."
    #license: "Apache 2.0"
    #file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}{{ if .Arm }}v{{ .Arm }}{{ end }}"
changelog:
  skip: true
