project_name: gotham

before:
  hooks:
    - go mod download

builds:
  - goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/gothamhq/gotham/common/hugo.buildDate={{.Date}} -X github.com/gothamhq/gotham/common/hugo.commitHash=

archives:
  - format: tar.gz
    name_template: "{{.ProjectName}}-v{{.Version}}-{{.Os}}-{{.Arch}}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: macos
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}-checksum.txt"

changelog:
  skip: true
