name: gotham
title: Gotham
summary: "An awesome and super fast Static Site Generator."
description: |
  Gotham is an awesome and super fast Static Site Generator. It's written in Go
  which is where it gets its speed. It can build Markdown into static and lean
  HTML, CSS, and JavaScript.

  Gotham is fully compatible with Hugo, from which it was "soft forked". You 
  can run `gotham version` to see which specific version of Hugo its compatible 
  with.
license: "Apache-2.0"
base: core20
grade: stable
confinement: strict
icon: "img/logo-icon-x1000.png"
adopt-info: gotham

apps:
  gotham:
    command: gotham
    completer: gotham-completion
    plugs:
      - desktop
      - home
      - network-bind
      - removable-media

parts:
  gotham:
    plugin: dump
    source: .
    override-build: |

      snapcraftctl build

      cp ./dist/gotham-linux_linux_amd64/gotham $SNAPCRAFT_PART_INSTALL
      chmod +x $SNAPCRAFT_PART_INSTALL/gotham

      $SNAPCRAFT_PART_INSTALL/gotham gen autocomplete --completionfile=./gotham-completion
      mv -v gotham-completion $SNAPCRAFT_PART_INSTALL/

      $SNAPCRAFT_PART_INSTALL/gotham version --type=short > VERSION
      snapcraftctl set-version v$(cat VERSION)
    stage-packages:
      - nodejs
      - npm

  pygments:
    plugin: python
    python-packages: [Pygments]
    prime:
      - bin/pygmentize
      - lib/python*/site-packages/Pygments-*.dist-info/*
      - lib/python*/site-packages/pygments/*
      - usr/bin/python*
      - -usr/bin/python*m
      - usr/lib/python*/*
      - -usr/lib/python*/distutils/*
      - -usr/lib/python*/email/*
      - -usr/lib/python*/lib2to3/*
      - -usr/lib/python*/tkinter/*
      - -usr/lib/python*/unittest/*
