name: gotham
title: Gotham
summary: "Gotham has been superseded by Strawberry"
description: |
  Gotham has been superseded by Strawberry. v0.13.0 is the last version called 
  Gotham. Please install Strawberry to continue receiving updates. Follow the 
  migration guide here: https://docs.strawberryssg.com/migration
license: "Apache-2.0"
base: core20
grade: stable
confinement: strict
icon: "img/logo-icon-x1000.png"
adopt-info: gotham

apps:
  gotham:
    command: gotham
    completer: gotham-completion
    plugs:
      - desktop
      - home
      - network-bind
      - removable-media

parts:
  gotham:
    plugin: dump
    source: ./dist
    override-build: |

      snapcraftctl build

      cp ./gotham-linux_linux_amd64/gotham $SNAPCRAFT_PART_INSTALL
      chmod +x $SNAPCRAFT_PART_INSTALL/gotham

      $SNAPCRAFT_PART_INSTALL/gotham gen autocomplete --completionfile=./gotham-completion
      mv -v gotham-completion $SNAPCRAFT_PART_INSTALL/

      $SNAPCRAFT_PART_INSTALL/gotham version --type=short > VERSION
      snapcraftctl set-version v$(cat VERSION)
    stage-packages:
      - git
      - nodejs
      - npm
  pygments:
    plugin: python
    python-packages: [Pygments]
    stage:
      - lib64/*
  nodejs:
    plugin: npm
    source: .
    npm-node-version: 12.19.0
    stage:
      - lib64/*
